[project]
name = "user"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.profiles]
path = "contracts/profiles.clar"
depends_on = []
